baseURL = "https://kairoscorp.github.io/"
DefaultContentLanguage = "en"

theme = "kairos-theme"
title = "Kairos"

[languages.en]
    weight = 20
    languageName = "English"
    languageCode = "en-uk"
    copyright = "All rights reserved."

    description = "The right tools at just the right time."

    [[languages.en.menu.main]]
        url    = "/"
        name   = "Home"
        weight = 0


[languages.fr]
    weight = 10
    languageName = "Français"
    languageCode = "fr-fr"
    copyright = "Alle Rechte vorbehalten."

    description = "what the hell Je ne c'est pas."

    [[languages.fr.menu.main]]
        url    = "/"
        name   = "Startseite"
        weight = 0
