baseURL = "https://kairoscorp.github.io/"
languageCode = "en-us"
title = "Kairos"
theme = "kairos-theme"

defaultContentLanguage = "en"

[languages]
[languages.en]
weight = 0
copyright = "&copy; 2016 Free HTML5. All Rights Reserved."
title = "My blog"

[languages.fr]
weight = 1
copyright = "Tout est à moi"
title = "Mon blog"
