baseURL = "https://kairoscorp.github.io/"
languageCode = "en-us"
title = "Kairos"
<<<<<<< HEAD
theme = "kairos-theme"
=======
theme = "kairos-theme"


DefaultContentLanguage = "en"

[params.navigation]
help  = "Help"

[Languages]
[Languages.en]
title = "My blog"
weight = 1
[Languages.en.params]
linkedin = "english-link"

[Languages.fr]
copyright = "Tout est à moi"
title = "Mon blog"
weight = 2
[Languages.fr.params]
linkedin = "lien-francais"
[Languages.fr.navigation]
help  = "Aide"
>>>>>>> Update URLs to support other languages
